### ISSUE TITLE
Allow non-float values in the parameters block

### ISSUE THREAD

**Issue by lukethehuman** [ScepticalRabbit/mooseherder#10]
I have a MOOSE input file with an existing parameters section containing string, float, int, and parsed values. The `InputModifier` class currently raises an error when encountering the strings and parsed values. It would be good to support these types of variable, as they are useful for parametric descriptions of geometry & simulation parameters.

The same issue could be minimally recreated by the following parameter block:
```
#_*
name=doubler
x=1
answer=$fparse{2 * x}
#__
```

**Comment by lukethehuman** [comment]
The full input file I'm using is here (note .txt format so github supports it): [monoblock.i.txt](https://github.com/ScepticalRabbit/mooseherder/files/13753482/monoblock.i.txt)

**Comment by ScepticalRabbit** [comment]
This has been added to the main branch with the latest pull request. A full test suite for string cases and parsed functions has been created for the input modifier to ensure it handles these cases into the future.
