### ISSUE TITLE
Ability to have single dictionary of input vars shared between MOOSE and Gmsh.

### ISSUE THREAD

**Issue by ScepticalRabbit** [ScepticalRabbit/mooseherder#18]
There are several cases where users will want to update variables of MOOSE and Gmsh at the same time but might not want to run all combinations of those variables between the two apps. The user should be able to specify a single list of variables and tell the herder which is which.

**Comment by fusmatrs** [comment]
I've built this kind of functionality into my optimisation code for now. It probably should live in the herder at some point as it would be much more convenient to just `run_once(dict)` rather than `run_once(moose_dict,gmsh_dict)`

**Comment by ScepticalRabbit** [comment]
Added with latest PR. The user now passes in a list of dictionaries for each combination of modifiers.
