### ISSUE TITLE
Keep all = False behaviour is not correct for n_moose < parameters

### ISSUE THREAD

**Issue by fusmatrs** [ScepticalRabbit/mooseherder#24]
Doesn't work for the situation where you dont want to keep all results, but do want to run multiple copies of moose in each dir

**Comment by fusmatrs** [comment]
Currently getting around it by having`keep_all=True` and then running `herd.clear_dirs()` and `herd.create_dirs()` before each parallel run.

**Comment by ScepticalRabbit** [comment]
This should be fixed with the latest PR. I have added this to the pytest suite so should stay fixed.
