### ISSUE TITLE
Not possible to run herd for multiple iterations and keep only current results that doesn't break other functionality

### ISSUE THREAD

**Issue by fusmatrs** [ScepticalRabbit/mooseherder#37]
Current functionality using `set_keep_flag = False` means that if you pass 8 variables and have `n_moose = 4` it overwrites the second run. i.e. you'll only have 4 results at the end, not 8.

Using `set_keep_flag = True` and wiping directories between runs means that `read_output_keys()` falls over as the earlier jsons are gone. 

There needs to be the intermediate case, where each run retains just the information from the current run. For my optimisations I will have many hundreds of runs so don't want to store all, but don't want to overwrite every individual run either so I can have more partcles in swarm or individuals in a GA than there are cores on a machine.

**Comment by ScepticalRabbit** [comment]
Pulled the fix from rs-merge branch
