### ISSUE TITLE
Reading results from Gmsh + MOOSE run errors

### ISSUE THREAD

**Issue by fusmatrs** [ScepticalRabbit/mooseherder#38]
Running Gmsh + MOOSE (Changing only gmsh). output_keys.json file has 'None', 'xxxxxxx.e' files as it should.
When the `SweepReader` iterates over the files, it's not catching the Nones. What is there is a `Path` with `str` 'None', not a `None` type. Will try and fix in rs_merge branch

**Comment by ScepticalRabbit** [comment]
Pulled the fix from rs-merge branch
